* Liftoff Coding Challenges :TOC:
  - [[#class-1---area-of-a-triangle][Class 1 - Area of A Triangle]]
  - [[#class-2---find-the-smallest-and-biggest-numbers][Class 2 - Find the Smallest and Biggest Numbers]]

** Class 1 - Area of A Triangle
Write a function that takes the base and height of a triangle and return its area.

*** Examples
triArea(3, 2) ➞ 3

triArea(7, 4) ➞ 14

triArea(10, 10) ➞ 50

*** Notes
The area of a triangle is: (base * height) / 2
Don't forget to return the result.
If you get stuck on a challenge, find help in the Resources tab.
If you're really stuck, unlock solutions in the Solutions tab.

*** My Solution
[[https://replit.com/@BrandonZamorano/01triArea#index.ts][Link to Replit]]
#+begin_src typescript
function triArea(base: number, height: number): number {
    return (base * height) / 2;
}
#+end_src

** Class 2 - Find the Smallest and Biggest Numbers
Create a function that takes an array of numbers and return both the minimum and maximum numbers, in that order.

*** Examples
minMax([1, 2, 3, 4, 5]) ➞ [1, 5]

minMax([2334454, 5]) ➞ [5, 2334454]

minMax([1]) ➞ [1, 1]
*** Notes
All test arrays will have at least one element and are valid.
*** My Solution
[[https://replit.com/@BrandonZamorano/02minMax#index.ts][Link to Replit]]
#+begin_src typescript
function minMax(nums: number[]): [min: number, max: number] {
    return [Math.min(...nums), Math.max(...nums)];
}
#+end_src
